# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('tier', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBooking', models.DateTimeField(verbose_name='date booked')),
                ('GSTNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSTNumber', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date cancelled')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('SSN', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('jobType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('type', models.CharField(max_length=20)),
                ('flightCode', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('arr', models.CharField(max_length=10)),
                ('dep', models.CharField(max_length=30)),
                ('soruce', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('time', models.DateTimeField(verbose_name='date booked')),
                ('_class', models.CharField(max_length=20)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Passenger')),
            ],
        ),
        migrations.AddField(
            model_name='cancel',
            name='cancellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Passenger'),
        ),
        migrations.AddField(
            model_name='book',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Passenger'),
        ),
    ]
