# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 04:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
